# Generated by Django 3.1.5 on 2021-03-01 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_User_Table',
            fields=[
                ('user_id', models.TextField(primary_key=True, serialize=False)),
                ('user_nickname', models.TextField()),
                ('gender', models.TextField()),
                ('age_range', models.TextField()),
                ('contact', models.TextField()),
                ('university', models.TextField()),
                ('preference', models.TextField(default='ALL')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('partner_user_id', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=0)),
                ('sign_up_date', models.DateField(default=datetime.date.today)),
                ('recent_matching_date', models.DateField(default=datetime.date(2021, 1, 1))),
                ('matching_count', models.IntegerField(default=0)),
                ('admin_allow', models.BooleanField(null=True)),
                ('Q01', models.BooleanField(null=True)),
                ('Q02', models.BooleanField(null=True)),
                ('Q03', models.BooleanField(null=True)),
                ('Q04', models.BooleanField(null=True)),
                ('Q05', models.BooleanField(null=True)),
                ('Q06', models.BooleanField(null=True)),
                ('Q07', models.BooleanField(null=True)),
                ('Q08', models.BooleanField(null=True)),
                ('Q09', models.BooleanField(null=True)),
                ('Q10', models.BooleanField(null=True)),
            ],
        ),
    ]
