# Generated by Django 3.1.5 on 2021-03-02 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered_user_table',
            name='Q01',
        ),
        migrations.RemoveField(
            model_name='registered_user_table',
            name='Q02',
        ),
        migrations.RemoveField(
            model_name='registered_user_table',
            name='Q03',
        ),
        migrations.RemoveField(
            model_name='registered_user_table',
            name='Q04',
        ),
        migrations.RemoveField(
            model_name='registered_user_table',
            name='Q05',
        ),
        migrations.RemoveField(
            model_name='registered_user_table',
            name='Q06',
        ),
        migrations.RemoveField(
            model_name='registered_user_table',
            name='Q07',
        ),
        migrations.RemoveField(
            model_name='registered_user_table',
            name='Q08',
        ),
        migrations.RemoveField(
            model_name='registered_user_table',
            name='Q09',
        ),
        migrations.RemoveField(
            model_name='registered_user_table',
            name='Q10',
        ),
        migrations.RemoveField(
            model_name='registered_user_table',
            name='admin_allow',
        ),
        migrations.RemoveField(
            model_name='registered_user_table',
            name='age_range',
        ),
        migrations.RemoveField(
            model_name='registered_user_table',
            name='image',
        ),
        migrations.RemoveField(
            model_name='registered_user_table',
            name='partner_user_id',
        ),
        migrations.RemoveField(
            model_name='registered_user_table',
            name='preference',
        ),
        migrations.RemoveField(
            model_name='registered_user_table',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='registered_user_table',
            name='university',
        ),
        migrations.RemoveField(
            model_name='registered_user_table',
            name='user_nickname',
        ),
    ]
