# Generated by Django 3.1.5 on 2021-03-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210302_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_user_table',
            name='university',
            field=models.TextField(default=''),
        ),
    ]
