# Generated by Django 3.1.5 on 2021-03-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_registered_user_table_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_user_table',
            name='last_partner_user_id',
            field=models.TextField(default=''),
        ),
    ]
