# Generated by Django 3.1.5 on 2021-03-02 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_registered_user_table_last_partner_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_user_table',
            name='last_update_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
