# Generated by Django 3.1.5 on 2021-03-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_registered_user_table_last_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_user_table',
            name='user_nickname',
            field=models.TextField(default=''),
        ),
    ]
