# Generated by Django 3.1.5 on 2021-01-31 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Table',
            fields=[
                ('user_code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('gender', models.BooleanField(default=True)),
                ('birth', models.IntegerField()),
                ('contact', models.CharField(max_length=30)),
                ('university', models.CharField(max_length=30)),
                ('preference', models.IntegerField(default=3)),
                ('image', models.ImageField(upload_to='')),
                ('priority', models.IntegerField(default=0)),
                ('sign_up_date', models.DateField(default=datetime.date.today)),
                ('recent_matching_date', models.DateField(default=datetime.date.today)),
                ('matching_count', models.IntegerField(default=0)),
                ('admin_allow', models.BooleanField(default=False)),
                ('Q01', models.BooleanField(default=True)),
                ('Q02', models.BooleanField(default=True)),
                ('Q03', models.BooleanField(default=True)),
                ('Q04', models.BooleanField(default=True)),
                ('Q05', models.BooleanField(default=True)),
                ('Q06', models.BooleanField(default=True)),
                ('Q07', models.BooleanField(default=True)),
                ('Q08', models.BooleanField(default=True)),
                ('Q09', models.BooleanField(default=True)),
                ('Q10', models.BooleanField(default=True)),
            ],
        ),
    ]
