# Generated by Django 3.1.5 on 2021-01-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Man',
            fields=[
                ('user_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=5)),
                ('birth', models.IntegerField(max_length=4)),
                ('contact', models.CharField(max_length=30)),
                ('university', models.CharField(max_length=30)),
                ('preference', models.IntegerField(max_length=1)),
                ('image', models.ImageField(upload_to='')),
                ('priority', models.IntegerField(default=0)),
                ('sign_up_date', models.DateField()),
                ('recent_matching_date', models.DateField()),
                ('matching_count', models.IntegerField(default=0)),
                ('admin_allow', models.BooleanField(default=False)),
            ],
        ),
    ]
