# Generated by Django 3.1.5 on 2021-02-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query_Table',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('selection1', models.TextField()),
                ('selection2', models.TextField()),
            ],
        ),
    ]
