# Generated by Django 3.1.5 on 2021-02-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_table',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
