# Generated by Django 3.1.5 on 2021-02-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_auto_20210220_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='query_table',
            name='query',
            field=models.TextField(blank=True, default=''),
        ),
    ]
