# Generated by Django 3.1.5 on 2021-02-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0004_auto_20210220_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_table',
            name='query',
            field=models.TextField(default='선택하세요!'),
        ),
    ]
