# Generated by Django 3.1.5 on 2021-02-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0006_auto_20210220_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_table',
            name='query',
            field=models.TextField(blank=True, default='선택하세요!', null=True),
        ),
    ]
