# Generated by Django 3.1.5 on 2021-02-08 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social_user',
            old_name='platform_name',
            new_name='platform',
        ),
    ]
