# Generated by Django 3.1.5 on 2021-02-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_user_table',
            name='image',
            field=models.ImageField(upload_to='social'),
        ),
    ]
