# Generated by Django 3.1.5 on 2021-02-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20210208_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_user',
            name='id',
        ),
        migrations.AlterField(
            model_name='social_user',
            name='user_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
