# Generated by Django 3.1.5 on 2021-02-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20210220_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_user_table',
            name='admin_allow',
            field=models.NullBooleanField(),
        ),
    ]
