# Generated by Django 3.1.5 on 2021-02-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20210220_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_user_table',
            name='admin_allow',
            field=models.BooleanField(null=True),
        ),
    ]
