# Generated by Django 3.1.5 on 2021-02-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20210220_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_user_table',
            name='Q01',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='social_user_table',
            name='Q02',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='social_user_table',
            name='Q03',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='social_user_table',
            name='Q04',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='social_user_table',
            name='Q05',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='social_user_table',
            name='Q06',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='social_user_table',
            name='Q07',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='social_user_table',
            name='Q08',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='social_user_table',
            name='Q09',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='social_user_table',
            name='Q10',
            field=models.BooleanField(null=True),
        ),
    ]
