# Generated by Django 3.1.5 on 2021-02-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20210220_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_user_table',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
