# Generated by Django 3.1.5 on 2021-02-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20210225_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_user_table',
            name='partner_user_id',
            field=models.TextField(default=''),
        ),
    ]
