# Generated by Django 3.1.5 on 2021-02-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_social_user_table_partner_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_user_table',
            name='partner_user_id',
            field=models.TextField(blank=True),
        ),
    ]
